### ISSUE TITLE
Parallel plugin crashes

### ISSUE THREAD

**Issue by chrisfilo** [smathot/OpenSesame#226]
Parallel plugin crashes when using psychopy backend (using both dev and stable versions of opensesame and psychopy. I'm using the following experiment file: https://raw.github.com/NeuroanatomyAndConnectivity/ConjunctiveContinuousPerformanceTask/master/CCPT.opensesame

    adenauer:/scr/adenauer1/PowerFolder/Dropbox/workspace/OpenSesame$ ./opensesame --debug
    debug.py(95).<module>: debug mode enabled (stacktrace off)
    __init__.py(27).<module>: redirect 'pyterm' module to libqtopensesame.widgets
    __init__.py(27).<module>: redirect 'statusbar' module to libqtopensesame.widgets
    __init__.py(27).<module>: redirect 'tree_overview' module to libqtopensesame.widgets
    __init__.py(27).<module>: redirect 'toolbar_items' module to libqtopensesame.widgets
    __init__.py(27).<module>: redirect 'variable_inspector' module to libqtopensesame.widgets
    __init__.py(27).<module>: redirect 'good_looking_table' module to libqtopensesame.widgets
    opensesame(95).<module>: no translator found for en_GB
    qtopensesame.py(87).resume_init: filesystem encoding: UTF-8
    qtopensesame.py(292).restore_config: 
    theme.py(53).__init__: theme = 'default' (resources/theme/default)
    theme.py(152).load_icon_map: using custom icon theme
    theme.py(161).load_icon_map: resources/theme/default/icon_map.csv
    theme.py(185).load_icons: 
    theme.py(185).load_icons: 
    experiment.py(126).__init__: creating new pool folder
    experiment.py(130).__init__: pool folder is '/tmp/tmpWrjEJK.opensesame_pool'
    experiment.py(506).open: opening from unicode string
    experiment.py(249).from_string: building experiment
    experiment.py(233).parse_definition: loading core item 'sequence' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created experiment
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created getting_started
    experiment.py(233).parse_definition: loading core item 'sketchpad' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = white
    color_edit.py(104).initialize: color = white
    color_edit.py(104).initialize: color = white
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created welcome
    qtopensesame.py(302).restore_state: 
    qtopensesame.py(325).restore_state: adding recent file '/home/raid3/gorgolewski/Desktop/counterbalancing.opensesame'
    qtopensesame.py(325).restore_state: adding recent file '/home/raid3/gorgolewski/workspace/ConjunctiveContinuousPerformanceTask/CCPT.opensesame'
    qtopensesame.py(325).restore_state: adding recent file '/home/raid3/gorgolewski/Desktop/Newexperiment.opensesame'
    qtopensesame.py(396).set_style: using style 'GTK+'
    toolbar_items.py(199).build: adding plugin 'text_display'
    toolbar_items.py(199).build: adding plugin 'auto_example'
    toolbar_items.py(199).build: adding plugin 'video_player'
    toolbar_items.py(199).build: adding plugin 'fixation_dot'
    toolbar_items.py(199).build: adding plugin 'form_multiple_choice'
    toolbar_items.py(199).build: adding plugin 'form_text_render'
    toolbar_items.py(199).build: adding plugin 'form_base'
    toolbar_items.py(199).build: adding plugin 'form_text_display'
    toolbar_items.py(199).build: adding plugin 'form_text_input'
    toolbar_items.py(199).build: adding plugin 'form_consent'
    toolbar_items.py(199).build: adding plugin 'text_input'
    toolbar_items.py(199).build: adding plugin 'touch_response'
    toolbar_items.py(199).build: adding plugin 'srbox'
    toolbar_items.py(199).build: adding plugin 'reset_feedback'
    toolbar_items.py(199).build: adding plugin 'port_reader'
    toolbar_items.py(199).build: adding plugin 'joystick'
    toolbar_items.py(199).build: adding plugin 'notepad'
    toolbar_items.py(199).build: adding plugin 'external_script'
    toolbar_items.py(199).build: adding plugin 'pp_io'
    toolbar_items.py(199).build: adding plugin 'repeat_cycle'
    toolbar_items.py(199).build: adding plugin 'parallel'
    toolbar_items.py(199).build: adding plugin 'advanced_delay'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'text_display'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'form_multiple_choice'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'form_text_render'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'text_input'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'touch_response'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'form_base'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'auto_example'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'srbox'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'form_text_display'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'reset_feedback'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'notepad'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'form_text_input'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'form_consent'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'parallel'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'advanced_delay'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'video_player'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'external_script'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'pp_io'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'port_reader'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'repeat_cycle'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'fixation_dot'
    qtopensesame.py(1313).populate_plugin_menu: found plugin 'joystick'
    qtopensesame.py(423).start_autosave_timer: autosave interval = 3660000 ms
    qtopensesame.py(509).set_unsaved: unsaved = False
    qtopensesame.py(592).check_update: opening http://files.cogsci.nl/software/opensesame/MOST_RECENT_VERSION.TXT
    qtopensesame.py(632).check_update: identifying as version 2.079914
    qtopensesame.py(633).check_update: latest stable version is 0.2704
    theme.py(185).load_icons: 
    theme.py(185).load_icons: 
    qtopensesame.py(1228).refresh: None
    qtopensesame.py(1046).build_item_list: None
    experiment.py(126).__init__: creating new pool folder
    experiment.py(130).__init__: pool folder is '/tmp/tmpS9ORea.opensesame_pool'
    experiment.py(515).open: opening .opensesame file
    experiment.py(249).from_string: building experiment
    experiment.py(233).parse_definition: loading core item 'sketchpad' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = white
    color_edit.py(104).initialize: color = white
    color_edit.py(104).initialize: color = white
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created show_blank
    experiment.py(233).parse_definition: loading core item 'feedback' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = white
    color_edit.py(104).initialize: color = white
    feedpad.py(55).static_items: variable property: color = [feedback_colour]
    color_edit.py(104).initialize: color = white
    feedpad.py(55).static_items: variable property: color = [feedback_colour]
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created feedback
    experiment.py(233).parse_definition: loading core item 'loop' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    theme.py(185).load_icons: 
    qtitem.py(778).auto_add_widget: 46461440
    qtitem.py(778).auto_add_widget: repeat
    qtitem.py(778).auto_add_widget: skip
    qtitem.py(778).auto_add_widget: order
    qtitem.py(778).auto_add_widget: offset
    qtitem.py(778).auto_add_widget: break_if
    qtitem.py(53).__init__: created training_loop
    experiment.py(233).parse_definition: loading core item 'sequence' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created sequence
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = None
    color_edit.py(104).initialize: color = None
    qtitem.py(53).__init__: created thank_you
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = None
    color_edit.py(104).initialize: color = None
    qtitem.py(53).__init__: created intro_1
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = None
    color_edit.py(104).initialize: color = None
    qtitem.py(53).__init__: created intro_2
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = None
    color_edit.py(104).initialize: color = None
    qtitem.py(53).__init__: created intro_3
    experiment.py(233).parse_definition: loading core item 'sketchpad' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = white
    color_edit.py(104).initialize: color = white
    color_edit.py(104).initialize: color = white
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created intro_4
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = None
    color_edit.py(104).initialize: color = None
    qtitem.py(53).__init__: created intro_5
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = None
    color_edit.py(104).initialize: color = None
    qtitem.py(53).__init__: created intro_6
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = None
    color_edit.py(104).initialize: color = None
    qtitem.py(53).__init__: created intro_7
    experiment.py(233).parse_definition: loading core item 'sketchpad' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = white
    color_edit.py(104).initialize: color = white
    feedpad.py(55).static_items: variable property: file = stimuli/[trial_shape].png
    color_edit.py(104).initialize: color = white
    feedpad.py(55).static_items: variable property: file = stimuli/[trial_shape].png
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created show_shape
    experiment.py(233).parse_definition: loading core item 'sequence' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created experiment
    experiment.py(233).parse_definition: loading core item 'inline_script' from 'libqtopensesame.items'
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created set_trial_variables
    experiment.py(233).parse_definition: loading core item 'inline_script' from 'libqtopensesame.items'
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created shuffle_stimuli_list
    experiment.py(233).parse_definition: loading core item 'logger' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created logger
    experiment.py(233).parse_definition: loading core item 'inline_script' from 'libqtopensesame.items'
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created prepare_feedback_message
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created parallel
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created parallel
    experiment.py(233).parse_definition: loading core item 'sequence' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created training_sequence
    experiment.py(233).parse_definition: loading core item 'sequence' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created stimuli_and_blank
    experiment.py(233).parse_definition: loading core item 'keyboard_response' from 'libqtopensesame.items'
    item.py(289).from_string: 
    theme.py(185).load_icons: 
    qtitem.py(53).__init__: created keyboard_response
    experiment.py(233).parse_definition: loading core item 'loop' from 'libqtopensesame.items'
    theme.py(185).load_icons: 
    theme.py(185).load_icons: 
    qtitem.py(778).auto_add_widget: 41182848
    qtitem.py(778).auto_add_widget: repeat
    qtitem.py(778).auto_add_widget: skip
    qtitem.py(778).auto_add_widget: order
    qtitem.py(778).auto_add_widget: offset
    qtitem.py(778).auto_add_widget: break_if
    qtitem.py(53).__init__: created loop
    qtopensesame.py(1228).refresh: None
    qtopensesame.py(1046).build_item_list: None
    theme.py(185).load_icons: 
    color_edit.py(104).initialize: color = None
    color_edit.py(104).initialize: color = None
    general_properties.py(234).refresh: 
    qtopensesame.py(509).set_unsaved: unsaved = False
    general_properties.py(139).apply_changes: 
    qtopensesame.py(1228).refresh: None
    qtopensesame.py(1046).build_item_list: None
    qtopensesame.py(1168).run_experiment: stopping autosave timer
    Fatal Python error: (pygame parachute) Segmentation Fault
    Aborted (core dumped)

**Comment by smathot** [comment]
The `parallel` plugin is now completely deprecated in favor of `coroutines`:

- http://osdoc.cogsci.nl/3.1/manual/structure/coroutines/
