### ISSUE TITLE
Reserved names

### ISSUE THREAD

**Issue by palday** [smathot/OpenSesame#247]
A list of reserved names would be useful for writing inline scripts. 

Concrete example: `end` is the name of the cleanup function run at the end of the experiment, but also a common enough variable name. Because script variables are actually fields on the `experiment` object, using something like the following gives a strange error when `end()` is called:

	my_canvas.show()
	start = self.time()
	key, end = my_keyboard.get_key()

OpenSesame's error doesn't help much:

    An unexpected error occurred, which was not caught by OpenSesame. This should not happen! Message:
    'int' object is not callable

When I looked up the file and line in the debug window, then looked at the source code, the problem was fairly obvious, but this won't be obvious to all users, even those using inline scripts. Part of the problem is the delay and the limited traceback: by the time this error occurs, I'm not even thinking about my `end` variable from two scripts back.

Alternatively, using the usual `_var` tricks to mask internal variables would also work (but probably be a much greater effort, as it would involve changing large parts of the code base).

**Comment by smathot** [comment]
Closing, because variable management has been reworked in OpenSesame 3. Reserved names are no longer an issue.
