### ISSUE TITLE
exp.set() and get() treat list with one item as OpenSesame variable

### ISSUE THREAD

**Issue by dschreij** [smathot/OpenSesame#258]
The following issue arises with the following code in an inline script:

    my_list = [1234]
    exp.set("log_list", my_list)
    print exp.get("log_list")

Running this results into:

    osexception: 
    Variable '1234' is not set in item 'experiment'.<br /><br />You are trying to use a variable that does not exist. Make sure that you have spelled and capitalized the variable name correctly. You may wish to use the variable inspector (Control + I) to find the intended variable.

This probably happens because exp.set() changes the [1234] from list a to a string, which is OS internal notation of specifying a variable. exp.get("log_list") will try to parse this "[1234]" and look for a variable with this name, which does no exist and as a result the experiment will crash

**Comment by smathot** [comment]
Closing, because the new variable management system has been implemented in OpenSesame 3.0.
