### ISSUE TITLE
Constraints and pseudo-randomization in loop item

### ISSUE THREAD

**Issue by esdalmaijer** [smathot/OpenSesame#272]
Feautre request: Adding more (pseudo-)randomisation options to the loop item, e.g. [Latin square](http://en.wikipedia.org/wiki/Latin_square) ([as requested on the forum](http://forum.cogsci.nl/index.php?p=/discussion/692/open-randomisation-of-image-selection-in-sketchpad)).

**Comment by smathot** [comment]
Fyi, I've been doing some work on a Python library for pseudorandomization that allows you to define constraints in a flexible way:

- <https://github.com/smathot/python-pseudorandom>

It's early days, but at some point I want to integrate this into OpenSesame. Let me know if you have suggestions!

**Comment by smathot** [comment]
As of v3.1, constraints can be applied through advanced loop operations:

- http://osdoc.cogsci.nl/3.1/manual/structure/loop/
