### ISSUE TITLE
Toolbox for miscellaneous but frequently used functions

### ISSUE THREAD

**Issue by dschreij** [smathot/OpenSesame#319]
(Feature request)

Often I find myself copy-pasting functions from experiment to experiment, because I use these functions virtually every time and they form the basis of many cognitive experiments. Think of calculating the positions for placing stimuli on a circle or on a grid. Isn't it a good idea to make an internal module in OpenSesame to contain these kind of frequently used functions and keep extending this module in the future? 

Two examples:

```python
def calculate_circle_positions(xc,yc,r,setsize):
	""" This function calculates the x,y coordinates of positions on a virtual 
	circle with radius r to place items on
	
	Parameters
	----------
	x : int
		x coordinate of the center of the circle
	y : int
		y coordinate of the center of the circle
	r : int
		the radius of the circle in pixels
	setsize : int
		the number of positions to be calculated on the circle. All positions are equidistant to each other
		
	Returns
	-------
	A list with the positions of the circle as (x,y) tuples
	"""

	from math import pi, cos, sin

	# Angle between two adjacent circle positions
	anglesegment = 2*pi/setsize					
	# Empty list to fill with circle positions
	circlepositions = []						
	
	# Calculate amount of circlepositions that is equal to setsize
	for i in range(0,setsize):
		x = r * cos(i*anglesegment) + xc
		y = r * sin(i*anglesegment) + yc
		circlepositions.append( (x,y) )
	return circlepositions

def calculate_grid_positions(grid_dimension, x, y, distance=50):
	"""
	Calculate positions of a grid
	
	Parameters
	----------
	grid_dimension : int
		The dimensions of the grid position, so for a 5x5 grid, this value should be
		5. (this needs to be improved so you can also create grids that are not square).
	x : int
		The center x coordinate around which the grid positions should be calculated.
	y : int
		The center y coordinate around which the grid positions should be calculated.
	distance : int, default 50
		The distance in pixels between two grid positions
		
	Returns
	-------
	A list with (x,y) tuples representing the gridpositions
	"""
	start_x = x - 0.5*distance*grid_dimension + 0.5*distance 	#leftmost x
	start_y = y - 0.5*distance*grid_dimension + 0.5*distance 	#topmost y

	# Empty list to store grid positions in
	gridpositions = []
	# Grid columns (x positions)
	for x_count in range(0,grid_dimension):					
		# Calculate x of current column of the grid (using x_count to indicate column)
		current_x = start_x + x_count*distance				
		# Grid rows (y positions)
		for y_count in range(0,grid_dimension):
			# Calculate y of current row of the grid (using y_count to indicate row)			
			current_y = start_y + y_count*distance			
			# Store calculated grid position in list
			gridpositions.append( (current_x, current_y) )
	return gridpositions
```
It might be nice if one could for instance do

```python
from libopensesame.misc import toolbox
cnvs = self.offline_canvas()
xc,yc = cnvs.xcenter(), cnvs.ycenter()
circle_positions = toolbox.calculate_circle_positions(xc,yc,250,8)
```

Of course, "toolbox" might not be the best name for the module, but if you like this idea, maybe we can think of something better!

**Comment by smathot** [comment]
Hi Daniel,

I don't really like the idea of having a toolbox with all kinds of functionality. It's bound to end up full of ad-hoc solutions that are only useful to a handful of people.

In some cases, it may make sense to add functions to existing modules though. For example, something like a `radial_to_xy()` that converts radial coordinates to cartesian coordinates may be a useful addition to the canvas back-end. But only functions that would really classify as being 'core' functionality (however vague that definition may be).

Alternatively, there could be a system that allows users to maintain a personal Python script to which they can add all kinds of functionality that they often use. And then there should be some way to include this script in the experiment, so that the experiment is still portable. That would avoid users from having to type the same code over and over again, without having to include an over-specialized Python module in OpenSesame--which, at any rate, will never satisfy everyone. I'm not sure what the best way to do so would be, but it might be a nice new extension. What do you think?

Cheers,
Sebastiaan

**Comment by dschreij** [comment]
I could work with a solution in which I could create and import my own module, and choose if it should be automatically included (in the file pool?) when OpenSesame detects this as necessary. One could place such a module in .opensesame folder maybe, where also the settings are kept?

**Comment by smathot** [comment]
Yes, something like. A custom file that is imported when an experiment is executed. Ideally, there would an extension that allows you to edit this file, and include it in OpenSesame when you want to distribute the experiment, for example by converting it to an `inline_script` item. Would you be interested in developing this?

**Comment by dschreij** [comment]
Sure, I'll try to make multiprocessing work with python3 first and then focus on this and the screenshot functionality

**Comment by smathot** [comment]
I added several commons to the Python API for OpenSesame 3.0 (as you probably know). This includes geometric functions like the one you're describing here:

- http://osdoc.cogsci.nl/3.0/python/common/

So I'll close this issue for now. Of course, if we feel that an extension will be necessary, then we can always open a new issue for that.

**Comment by dschreij** [comment]
Nice! I like this addition
