### ISSUE TITLE
File pool is empty when double clicking a .opensesame.tar.gz file

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#320]
The File pool appears to be empty when double clicking a .opensesame.tar.gz file in OpenSesame 2.9.5 on Windows7 (64bit). When clicking the refresh button the file(s) appear(s). The problem doesn't occur when opening the same .opensesame.tar.gz file from within an already running OpenSesame.

**Comment by smathot** [comment]
Confirmed, and thanks!
