### ISSUE TITLE
logfille parameter in opensesamerun cannot contain non-ascii characters

### ISSUE THREAD

**Issue by dev-jam** [smathot/OpenSesame#323]
When starting opensesamerun from cmdline and parameter --logfile contains non-ascii characters the following error is raised:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 51: ordinal not in range(128)

Traced the bug to line 739 and 740 in libopensesame/experiment.py:

        debug._print(u"experiment.init_log(): using '%s' as logfile (%s)" % \
            (self.logfile, self.encoding))

**Comment by smathot** [comment]
Hi Bob,

Thanks for spotting this one!

Cheers,
Sebastiaan
