### ISSUE TITLE
psycho back-end errors when StandalonePsychoPy window type is set to pygame

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#331]
Using a completely clean Windows 7 (64 bit) computer I installed opensesame_2.9.6-win32-1.exe
Changed the back-end of the Default template to psycho > runs without a problem.

Installed StandalonePsychoPy-1.82.01-win32.exe > Default template still runs without a problem.

Set PsychoPy Preferences > General > window type > from pyglet to pygame > error:

_________________________________________________________________________________
Unexpected error
line: 403
exception message: 'pygame.Surface' object has no attribute 'set_caption'
exception type: AttributeError

Traceback (also in debug window):
  File "dist\libqtopensesame\misc\process.py", line 139, in run
  File "dist\libopensesame\experiment.py", line 338, in run
  File "dist\libopensesame\experiment.py", line 723, in init_display
  File "dist\openexp\canvas.py", line 66, in init_display
  File "dist\openexp\_canvas\psycho.py", line 403, in init_display
AttributeError: 'pygame.Surface' object has no attribute 'set_caption'
_________________________________________________________________________________

When setting the window type back to pyglet the problem is gone. This also occurred on several lab computers where some users use OpenSesame and others use StandalonePsychoPy.

**Comment by smathot** [comment]
Thanks for pointing this one out!
