### ISSUE TITLE
hiding blocks of code in overview area seems to be inconsistent

### ISSUE THREAD

**Issue by eort** [smathot/OpenSesame#336]
Hi,

Clicking on the little arrows that are supposed to hide a block of code (e.g. a sequence) doesn't always hide the chosen block, but instead re-shows the previously hidden block. For example, I have one experimental and one practice sequence in my experiment. After having hidden one of them, trying to hide the second one, will make the first one re-appear. This happens regardless of which sequence was chosen first and also of the position in the experimental hierarchy.
However, it *does* work sometimes, if I first click outside of the overview area, before choosing the second sequence. I was playing around a bit, but failed to find any consistent pattern of cases, in which it works and those, in which it doesn't.

**Comment by smathot** [comment]
Hi Eduard,

And thanks again! I see what you mean. My guess is that it has something to do with the item overview being rebuild (which leads to all items being unfolded) in some situations. But I'll have to delve a little deeper.

Cheers,
Sebastiaan
