### ISSUE TITLE
Loop item disappears when dragged on another loop item

### ISSUE THREAD

**Issue by eort** [smathot/OpenSesame#337]
Hi, 

When a loop item is dragged onto another loop item in the overview area, former is moved to trash, even if you chose "cancel" in the window that pops up during this action. 
Surely, trying to perform this action doesn't make much sense, it still sucks having to recover your loop, if it happens accidentally.

**Comment by smathot** [comment]
Hi Eduard,

Thanks for spotting this one. Indeed, and the same things happens when dragging a `sequence` onto a `sequence`.

Cheers,
Sebastiaan
