### ISSUE TITLE
Bug: Item drag and drop into 'unused items' behaves strangely

### ISSUE THREAD

**Issue by EruIluvatar** [smathot/OpenSesame#343]
I wanted to drag a sketchpad-item into the (maximised) unused-item list, which already contained other elements.
After dropping the item, the cursor goes 'loading' (turning circle in windows) and only the strong green line between the original items remains. The item itself is neither visible in the list, nor is the item-count of 'unused items' increased. This bug is reproducable for me.

EDIT: Seems like moving around items in the 'unused items'-list suffers from this bug as well. So simply moving an object inside the list leads to the same behavior. Also moving an item from the experiment to a specific position in the list doesn't work.

OS: Windows 7 64bit
Version: OpenSesame 2.9.6

![opensesame_bug1](https://cloud.githubusercontent.com/assets/5493667/8719226/43724336-2baa-11e5-9cf5-4d100f95f72e.PNG)
![opensesame_bug2](https://cloud.githubusercontent.com/assets/5493667/8719225/4371a96c-2baa-11e5-88da-3655b266df13.PNG)

**Comment by smathot** [comment]
Thanks for reporting this!

**Comment by smathot** [comment]
Hi,

Would you mind giving the latest 2.9.7 prerelease a go, to see if this problem is resolved? This should fix a number of and drag-and-drop problems, including this one.

- http://files.cogsci.nl/software/opensesame/pre-releases/

Cheers,  
Sebastiaan

**Comment by EruIluvatar** [comment]
Hi Sebastiaan

Dropping a new item into unused items list is not working.

- If the list is empty, the hover-over pointer also does not even indicate
that it should be possible.
- If there are elements in the list and it's maximized, the item is not
added despite the pointer indicates that it should work (also the green bar
shows up).
- Additionally, the unused items - list is minimized every time a new or
existing item is dropped or even moved (if its allowed at this position). I
don't think this behavior is intended.


Seems like these points need some more work, however the green bars I've
described in the bug report are gone.

Also sorry I can't contribute the code myself, I'm busy with exams at the
moment.

Thanks for your work


Cheers,

Stefan

2015-07-27 16:33 GMT+02:00 Sebastiaan Mathot <notifications@github.com>:
