### ISSUE TITLE
Feature request: Add 'delete permanently' to context menu of items in 'unused items'-list

### ISSUE THREAD

**Issue by EruIluvatar** [smathot/OpenSesame#344]
When I have to create the biggest part of an experiment using inline-scripts, I like to create some sketchpad-items and put them into the 'unused items'. This way I can reference them from inside the scripts but they're not in the flow of the experiment.

At the moment you can only delete all unused items at once (from context menu of 'unused items'-entry). This way I have to move all the usefull items to the experiment to permanently delete all the unwanted items and move them back again.

Would be helpful if single items could be deleted permantly, like in the trash bin of Windows 7.

**Comment by smathot** [comment]
That seems like a reasonable, minor improvement.
