### ISSUE TITLE
IPython in debug window does not execute statement on enter press

### ISSUE THREAD

**Issue by dschreij** [smathot/OpenSesame#362]
Platform: Ubuntu 14.04
Version: 3.0.2

The IPython interpreter in the debug window does not execute any statements after pressing enter, but simply goes to the next line. It already occurs with a simple statement like print(modules()) or print(5). Another strange thing is that in OpenSesame on Ubuntu the interpreter initially shows

```
Python 2.7.6

* Type "help()", "copyright()", "credits()" or "license()" for more information.
* Type "print(modules())" for details about installed modules and version information.
* Use the "print([msg])" function in inline_script items to print to this debug window.
* Inspect inline_script variables when an experiment is finished.

In [1]:
```

while on other platforms the IPython version number is also mentioned (if I recall this correctly). So this might have something to do with it (as in the IPython intepreter not correctly initialized.)

**Comment by smathot** [comment]
This probably has to do with the older version of IPython on Ubuntu 14.04 (I use 15.10). I'll take a look at it.

**Comment by smathot** [comment]
I just tested it in a VirtualBox, and for me it works fine. This is a fresh, updated install of Ubuntu 14.04 (64 bit) with OpenSesame installed from the `ppa:smathot/cogscinl`. Is there something special about your environment?

Version info:

~~~
In [1]: print(modules())
OpenSesame 3.0.2
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
OpenCV is not available
OpenCV 2 is not available
QProgedit 3.2.0
Expyriment  (Python 2.7.6)
IPython 1.2.1
NumPy 1.8.2
PIL is available (version is unknown)
PsychoPy 1.79.01
PyAudio 0.2.7
PyGame 1.9.1release
PyGaze is not available
Pyglet 1.1.4
PyOpenGL 3.0.2
PyQt 4.10.4
PySerial 2.6
python-bidi is not available
python-markdown 2.4
SciPy 0.13.3
~~~

**Comment by dschreij** [comment]
I can't run the print(modules()) statement because I can't execute it :(

My IPython is version 4.0.0

I keep my python stack updated

**Comment by smathot** [comment]
> My IPython is version 4.0.0

That's probably it then. How did you update IPython? From a ppa somewhere?

**Comment by smathot** [comment]
Even after updating to IPython 4.0.0 using `pip install jupyter`, I cannot reproduce the problem. I do see the warnings that you already reported on Mac OS though:

~~~
sebastiaan@virtual-trusty:~$ opensesame
/usr/local/lib/python2.7/dist-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/qtconsole/rich_jupyter_widget.py:366: UserWarning: RichIPythonWidget is deprecated, use RichJupyterWidget
  warn("RichIPythonWidget is deprecated, use RichJupyterWidget")
~~~

So those should be caught.

Just to ask obvious: IPython does work properly when you start it on its own?

**Comment by dschreij** [comment]
IPython does work when I start it on its own. I also found out I can execute statements in OpenSesame  by pressing shift+enter instead of just enter. Here's my modules:

```
OpenSesame 3.0.2
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2]
OpenCV is available (version is unknown)
OpenCV2 2.4.9
QProgedit 3.2.0
Expyriment  (Python 2.7.9)
IPython 4.0.0
NumPy 1.9.2
PIL is available (version is unknown)
PsychoPy 1.82.01
PyAudio 0.2.8
PyGame 1.9.1release
PyGaze 0.5.0
Pyglet 1.1.4
PyOpenGL 3.1.0
PyQt 4.11.3
PySerial 2.6
python-bidi 0.3.4
python-markdown 2.6.1
SciPy 0.14.
```

**Comment by smathot** [comment]
Right, so you have upgraded Python itself as well: 2.7.6 → 2.7.9.

`pip --update` ← That's not a valid command. What did you do to upgrade exactly?

**Comment by dschreij** [comment]
Sorry, I just updated my Ubuntu distro from 14.04 to 15.04 this morning (And plan to go to 15.10 tonight), that's why the Python version changed, but the shift+enter solution already worked in 14.04. The full pip command to update ipython was:
```sudo pip install ipython --upgrade```

**Comment by smathot** [comment]
I haven't seen this problem for a while now, so let's close.
