### ISSUE TITLE
Responses not or incidentally registered in legacy backend on OSX

### ISSUE THREAD

**Issue by dschreij** [smathot/OpenSesame#367]
Version 3.0.2
Platform: OSX Yosemite

The legacy backend on OSX appears to only sparsely register key presses. I assume this is due to the new multithreaded architecture of OS3 (is this the case? as you now can also pause experiments). I know multithreading causes headaches when it comes to monitoring input as on every platform the thread expected to monitor input and the one to render the graphics (as in which is the main thread and which the child) is different on every platform.

**Comment by smathot** [comment]
There is a regular Python thread running in the background that occasionally sends 'heartbeats'. The idea is:

1. Once every second, `libopensesame.heartbeat.heartbeat` calls `experiment.transmit_workspace`
2. `experiment.transmit_workspace` pickles the `global`s dict of the Python workspace, and sends this through the output channel--if there is one.
3. The `multiprocess_runner` listens to the output channel, and if it finds a heartbeat, it updates the console and variable inspector.

The heartbeat is only started when the experiment is run in a window, and when there is an output channel (i.e. when using the `multiprocess_runner`). So: Do the key press problems go away when you run the experiment full screen?

**Comment by dschreij** [comment]
Just as an update, I don't seem to have this problem anymore with 3.0.5 at first sight, but I also have not extensively tested this yet.
