### ISSUE TITLE
Log-file location not updated when saving experiment to a different location

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#370]
The log-file location is not updated when saving an experiment to a different location. I tested this with OpenSesame 3.0.2 on Windows 7 (x64) but the same goes for OpenSesame 2.9.7

When opening an experiment like C:/test.osexp a *Quick run* will output the file C:/quickrun.csv like expected.
When saving it to C:/**TEMP**/test.osexp using *Save as*, a *Quick run* will still output C:/quickrun.csv until you reopen the file from C:/**TEMP**/test.osexp (without having to restart OpenSesame by the way).

This is especially uncomfortable when opening a file from an email because the log-file location will stick to something like *C:\Users\[username]\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.Outlook\N36QY7R0\* even after saving it to another location, until you reopen the experiment from that location.

**Comment by smathot** [comment]
Hi Jarik,

Good point. What do you think the most sensible behavior would be? That is, what's the suggested logfile location:

- When there's no default location yet?
- After you save/ open an experiment?
- After you have selected a logfile location when running an experiment?
- etc.

Cheers,
Sebastiaan

**Comment by JdenHartog** [comment]
Hi Sebastiaan,

It all seems pretty sensible to me already (except for the issue this started out with).

* When there's no default location yet?
 * Last know location makes sense to me as well as
 * *AppData* or
 *  *My Documents*
* After you save/ open an experiment?
 * Definitely the location of that experiment!
* After you have selected a log file location when running an experiment?
 * Holding on to that location until OpenSesame is closed, makes sense to me
* etc.
 * As long as it is consistent any location will do, I would prefer location of the experiment for:
   * File > Save as
    * File > Open
    * Run fullscreen (holding on to different location during OpenSesame 'session')
    * Run in window (holding on to different location during OpenSesame 'session')
    * Quick run
    * File pool > Add file

Hope this helps!

Best,
Jarik

**Comment by smathot** [comment]
The only thing I changed now, and which seems to work intuitively, is that the logfile path is now changed also when the experiment is saved using "save as".

**Comment by JdenHartog** [comment]
Thanks! This works perfect for me!
