### ISSUE TITLE
Experiment not executed after opening Back-end settings (psychopy)

### ISSUE THREAD

**Issue by eort** [smathot/OpenSesame#379]
Under the `psychopy` back-end, opening the tab `back-end settings` will cause the experiment to finish successfully, before it actually started, from the second run on. That is, once `back-end settings` were opened, the experiment will run once more perfectly fine, however, from then on the problem occurs every time.  It is reproducible with the default template (on Ubuntu 14.04). Loading a new experiment, or changing the back-end back and forth doesn't solve the issue. The only that help is restarting Opensesame entirely.

**Comment by smathot** [comment]
I see what you mean (I think):

1. Start OpenSesame
2. Select psycho back-end
3. Open back-end settings
4. Launch experiment (works)
5. Launch experiment again (doesn't work anymore)\

Is that what you mean as well?

**Comment by eort** [comment]
Precisely. That's the issue.

**Comment by smathot** [comment]
Closing this because I suspect it's been resolved with system updates over time. (If not feel free to ping me and I will re-open it.)
