### ISSUE TITLE
OpenSesame Run does not support .osexp filename extension in Browse-GUI

### ISSUE THREAD

**Issue by EruIluvatar** [smathot/OpenSesame#385]
Trying to open an experiment using the osexp-format, the OpenSesame Run utility doesn't allow to select files with this filename ending. Only .opensesame.tar.gz and .opensesame are allowed.

However, if the opensesamerun utility is used with proper command line options (the GUI doesn't show up then), experiments using .osexp extension are run as expected. So it's only a GUI problem.

Using Win 8.1 and OpenSesame latest stable version 3.0.4

**Comment by smathot** [comment]
Thank you!
