### ISSUE TITLE
Auto_example plug-in loses grayed out state when reopening experiment

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#389]
Think  I have a similar problem as described here #347

When using the *auto_example* plug-in in OpenSesame 3.0.5 the *Enter text* field is correctly grayed out when I uncheck the *Example checkbox*. (This state stays correct when I switch items.) When I save and reopen the experiment the *Example checkbox* is still unchecked as it should be, but the *Enter text* field is enabled.

**Comment by smathot** [comment]
Thanks!

**Comment by JdenHartog** [comment]
Thank you very much for this fix!

Another question regarding this subject if I may (I'm also willing to create another issue or a forum post off course).

When connecting the checkbox to the spinbox_widget by changing `line_edit_widget` to `spinbox_widget` from line 117 in *auto_example.py*. The 'loses grayed out state' problem is back. The *Enter value* field already loses its grayed out state when switching items. This is actually the problem I described here #347. I tried to override `edit_widget` like you suggested, but I can't get is to work.

I attached my *auto_example.py* below. Please remove the '.txt' extension before use :grin:
[auto_example.py.txt](https://github.com/smathot/OpenSesame/files/105225/auto_example.py.txt)

**Comment by smathot** [comment]
Hi Jarik,

I think that this is mostly a matter of getting to grips with Qt's signal-slot framework--not directly related to how OpenSesame plug-ins work. But it can be tricky, so please open a forum topic for it if you get stuck. (If it turns out to be a bug in the plug-in framework, we can always open a new issue later.)

Cheers,
Sebastiaan
