### ISSUE TITLE
Sound sampler does not block on first time playback of sound

### ISSUE THREAD

**Issue by dschreij** [smathot/OpenSesame#401]
OS 3.0.6 - All platforms

The first time the sampler plays a sound it does not block the experiment, even when the duration field of a sound sampler is set to "sound". On all following playbacks it does show the intended behavior.

**Comment by smathot** [comment]
Found it. For now, given that the issue has come up a few times on the forum, a workaround is:

Add an `inline_script` item just before the `sampler` or `synth` item, and add the following line to the *run* phase (replace 'my_sampler' by the name of the `sampler` or `synth` item):
~~~
items['my_sampler'].sampler.block = True
~~~
