### ISSUE TITLE
Clicking on item does not retract expanded item window after stopping experiment

### ISSUE THREAD

**Issue by Klemtonius** [smathot/OpenSesame#405]
Normally, the expanded item window will retract itself when an item is clicked, so that the item can be dragged and dropped into the overview window. However, this doesn't happen right after the experiment was run.

**Comment by smathot** [comment]
I think this (see commit) should fix the issue, but it's a bit finicky and seems to depend on the operating system. Could you verify whether it is indeed resolved once I release the next pre-release (3.1.3a6, somewhere this week or next)?
