### ISSUE TITLE
unwanted conversion of strings when set as attribute of var.

### ISSUE THREAD

**Issue by eort** [smathot/OpenSesame#409]
Hi, 

When a string that contains a number (e.g. `10`) is set as an attribute of var, the type is converted to an integer. I can see why this could be handy, but when someone doesn't know that, it can be pretty annoying finding out, why a script doesn't work. 

~~~.python
var.no = '10'
print var.no == '10' # prints False (quite surprisingly)
~~~

Eduard

**Comment by smathot** [comment]
Hi Eduard,

This implicit type conversion is quite central to how OpenSesame works. It makes it possible, for example, to do numeric comparisons in run-if statements, without specifying that the variable in question is numeric. But I can see why it can be confusing. Given that this is not a bug that can, or should be, fixed, do you have ideas about how it can be made less confusing?

Cheers,
Sebastiaan

**Comment by cpicanco** [comment]
Improve documentation?

**Comment by eort** [comment]
Indeed, this seems to make most sense. Maybe we can put it under usage or misc?

**Comment by smathot** [comment]
There is a section on variable typing already:

- http://osdoc.cogsci.nl/usage/variables-and-conditional-statements/#smart-variable-typing-and-some-pitfalls

You'll see that behavior can actually be even weirder than what you're describing, although only in rare cases.

However, given that users (nor you, apparently!) tend not to read the documentation, I was thinking more along the lines of a warning, or some kind of user message that appears in some cases. I'll think about it.

**Comment by cpicanco** [comment]
Hi @smathot, I am a new user so take my words wisely. Please consider the follow:

- Warnings for "educational purposes" would motivate a demand for verbose control by experts.
- The present issue is about an "assignment", something very basic even for beginners;
- I checked the docs. Pretty dense, I think. You have just confirmed with an non-systematic observation (without data) that some users "tend not to read the documentation". Well, if it is true, my argument persists. Documentation should be improved considering its mean audience and segmented accordingly (for different audiences). I understand that it is not an easy task and its is time consuming, but good docs tends to produce good excellent skills in good people.
