### ISSUE TITLE
mouse_response plugin not working any longer

### ISSUE THREAD

**Issue by mariansauter** [smathot/OpenSesame#414]
With 3.0 there have been some changes to the getClick() function which produce TWO errors.

The new code produces INDEX UT OF BOUNDS exceptions.

NEW CODE
```
    while True: 
    time = self.experiment.clock.time()
    buttons, times = self.mouse.getPressed(getTime=True)
    for i in (1,2,3):
    if buttons[i-1] and (buttonlist is None or i-1 in buttonlist): **# FIRST ERROR HERE**
        button = i
					pos = self.mouse.getPos()
					time = times[i] **# SECOND ERROR HERE**
					break
			else:
				if timeout is not None and time-start_time >= timeout:
					break
				continue
			break
```

FIRST ERROR: must be `i` instead of `i-1`

SECOND ERROR:
If I correct it to `[i-1]` it gets stuck in some weird semi-endless loop.
Uncommenting it, makes the code work. I don't kno why this "timing control" is implemented in the first place. Seems unneccesary.

Cheers!

**Comment by smathot** [comment]
Thanks!
