### ISSUE TITLE
Markdown on Linux Mint 17.3 (like Ubuntu Trusty)

### ISSUE THREAD

**Issue by palday** [smathot/OpenSesame#429]
The version of Python Markdown (2.4) available through the standard repos does not support the keyword argument `title` for `TocExtension` method, which leads to an incomplete initialisation at startup, cryptic error messages for users not familiar with Python and an unusable interface (for a standard installation via the PPA).  Installing the most recent version of Markdown via `pip` solves the problem -- assuming a standard configuration, you can even do this for a user-local installation.

Instead of just trying to import Markdown (in `libqtopensesame/misc/markdown_parser.py`) it might make sense to have a version check thrown in there as well for older versions. This is an easy fix and I'm happy to do a pull-request for it if you're interested in that solution.

**Comment by smathot** [comment]
Thanks for pointing this out.

> Instead of just trying to import Markdown (in libqtopensesame/misc/markdown_parser.py) it might make sense to have a version check thrown in there as well for older versions. This is an easy fix and I'm happy to do a pull-request for it if you're interested in that solution.

Yes, please do! Then I'll merge it asap into an early pre-release for 3.1.1, and push that version only to the ppa for Trusty and earlier.

**Comment by palday** [comment]
Done.
