### ISSUE TITLE
Enter (newline) after logger custom variable causes crash on reloading

### ISSUE THREAD

**Issue by alisdt** [smathot/OpenSesame#438]
Steps to reproduce:

1. Add a logger to an experiment
2. Uncheck "Log all variables (recommended)"
3. Click on "Add custom variable"
4. Type a valid variable name, and hit Enter at the end
5. Save the experiment
6. Attempt to reload the experiment

The experiment fails to load.

![osbug_variable_name](https://cloud.githubusercontent.com/assets/3340195/17019110/be6702d2-4f32-11e6-9c51-adca46780927.png)

 On inspection, the experiment file has a broken line, leaving a quote stranded on the next line:

    define logger new_logger
            set description "Logs experimental data"
            set auto_log no
            log "my_var1
    "

**Comment by alisdt** [comment]
Looks like the name with newline is considered a valid variable name, as long as there is nothing after it:

    >>> re_valid_var_name = re.compile(r'^[_a-zA-Z]+[_a-zA-Z0-9]*$')
    >>> re_valid_var_name.match("myvar1")
    <_sre.SRE_Match object at 0x7fb62dd4a440>
    >>> re_valid_var_name.match("myvar1\n")
    <_sre.SRE_Match object at 0x7fb62dd4a6b0>
    >>> re_valid_var_name.match("myvar1\nmyvar2")
    >>>

**Comment by alisdt** [comment]
I should say, the regular expression above is taken from line 71 of libopensesame/syntax.py which is what is used to check that variable names are valid in this case.

**Comment by alisdt** [comment]
This can be fixed by using \A and \Z instead of ^ and $, and re.MULTILINE, so the newline isn't given any special treatment:

    >>> re_valid_var_name = re.compile(r'\A[_a-zA-Z]+[_a-zA-Z0-9]*\Z', re.MULTILINE) 
    >>> re_valid_var_name.match("myvar1")
    <_sre.SRE_Match object at 0x7fb62dd4a440>
    >>> re_valid_var_name.match("myvar1\n")
    >>> re_valid_var_name.match("myvar1\nmyvar2")

**Comment by smathot** [comment]
Thank you for a very clear bug report! This should be easily fixed for the next maintenance release.

**Comment by smathot** [comment]
I think the `re.MULTILINE` is not necessary. Just using `\A` and `\Z` does the trick. Could you confirm that?

**Comment by alisdt** [comment]
Yes, that's right -- I wasn't sure if it would be needed to treat newline as an ordinary character, and must have got mixed up while testing possibilities. Thanks for the speedy fix!
