### ISSUE TITLE
OpenSesame 3.1.1 doesn't open the experiment when double clicking an .osexp file

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#441]
When double clicking an .osexp file (stored on the desktop) OpenSesame does open but the file isn't opened in OpenSesame. When clicking *File* >> *Open...* I am able to open the experiment.

I think this started with version 3.1.x and wasn't a problem on 3.0.7

I tested this on a clean 64 bit Win 7 system after installing opensesame_3.1.1-py2.7-win32-1.exe

Best,
Jarik

**Comment by smathot** [comment]
Hi Jarik,

This actually the same as #437, which is already fixed. Would you mind seeing if the fix described there works for you (i.e. updating the `opensesame-windows-launcher`)?

Cheers,
Sebastiaan

**Comment by JdenHartog** [comment]
Hi Sebastiaan,

Ah. I did search the open issues as I though this should be already reported by someone.
Next time should I check both *open issues* and *closed issues with milestone:3.1.x*?

I can confirm updating the opensesame-windows-launcher (with cmd.exe started as Admin) works.

Best,
Jarik

**Comment by smathot** [comment]
> Next time should I check both open issues and closed issues with milestone:3.1.x?

Right now yes, but perhaps I should change that policy, and only close issues once OpenSesame has actually been released with the fix.
