### ISSUE TITLE
Pressing cancel on file pool file dialog causes crash

### ISSUE THREAD

**Issue by dschreij** [smathot/OpenSesame#445]
**OS** 3.1.2

After pressing cancel on the file pool's file selection dialog, the following stack trace is shown:
~~~python
Traceback (most recent call last):
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/widgets/pool_widget.py", line 145, in select_and_add
    cfg.default_pool_folder = os.path.dirname(path_list[0])
IndexError: list index out of range
~~~

**Comment by smathot** [comment]
Thanks for spotting this one. It's a Qt5 issue that results from your own commit (797e56b), so that could've used a bit of testing at the time. In any case, it was easily fixed.
