### ISSUE TITLE
IPython debug window doesn't auto scroll down with text

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#474]
From OpenSesame 3 the new IPython debug window does not automatically scroll down with the text printed. This means the output of the code below in an `inline_script` item will not be visible until the experiment exits. Interestingly clicking the _Run selected text_ button in the `inline_script` item will keep the last line visible.

```
for x in range(0, 30):
    print "We're on time %d" % (x)
```

I tested this with OpenSesame 3.1.3a9 Jazzy James on Win7x64

**Comment by smathot** [comment]
Thanks! That's indeed a bit annoying.

**Comment by JdenHartog** [comment]
Indeed! Another possibly related thing (if you want me to create a new issue please let me know) is typing `modules()` in the *Debug window* no longer works. Although I guess doing *Tools > System information* basically replaces that...

**Comment by smathot** [comment]
Yes, the `modules()` function has been replaces by the System Information extension. Do you think there's still a reason to have `modules()` function?

**Comment by JdenHartog** [comment]
No, for me there's no reason to have `modules()` function.
I improved the *System Information* extension here https://github.com/smathot/OpenSesame/pull/492

**Comment by JdenHartog** [comment]
:+1: Nice addition to activate the System Information extension when calling modules() :exclamation:
