### ISSUE TITLE
Unfilled ellipses/ circles in legacy and psycho backends are not transparent

### ISSUE THREAD

**Issue by smathot** [smathot/OpenSesame#485]
If you draw an unfilled ellipse (or circle) in the legacy or psycho backends, you actually get an ellipse that has a smaller ellipse in it filled with the background color. Therefore, unfilled ellipses hide what's underneath, which is counterintuitive.

Perhaps we can adapt the solution used by expyriment for this, but we have to look into it.

**Comment by dschreij** [comment]
Just a 'ping' that this issue is still on my to-do list to solve. I'm just a bit occupied with other stuff at the moment, but hope to tackle this soon.

**Comment by smathot** [comment]
Solved for *legacy* backend in #497. *Psycho* still open.
