### ISSUE TITLE
Psychopy backend causes segmentation fault  (in Ubuntu 16.10? or in Jazzy?)

### ISSUE THREAD

**Issue by wkruijne** [smathot/OpenSesame#486]
Hey there,

I'm experiencing annoying segfault behavior when running psychopy-backend experiments since the recent upgrades of both ubuntu and opensesame (and I don't know which of the two is critical). As soon as I hit any type of run on any experiment  opensesame crashes  entirely  through a segfault:

```
wouter@WK-LT: ~/ $ opensesame --version
3.1.4b1 'Jazzy James'
wouter@WK-LT: ~/ $ opensesame
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
AL lib: (WW) ALCjackBackendFactory_init: jack_client_open() failed, 0x11
AL lib: (WW) alc_initconfig: Failed to initialize backend "jack"
Fatal Python error: (pygame parachute) Segmentation Fault
Aborted (core dumped)
```
Experiments run fine with other backends. Any thoughts on where to look for the solution to this?
W

**Comment by dschreij** [comment]
It seems to be a problem with the OpenAL sound driver. At least, that's were I find this function
`ALCjackBackendFactory_init`. See https://github.com/kcat/openal-soft/blob/master/Alc/backends/jack.c. Can't really say anything more about this though. Googling the message "jack server is not running or cannot be started" delivered some potential solutions though: http://askubuntu.com/questions/557906/problem-starting-jack-server-jack-server-is-not-running-or-cannot-be-started. Could you try that?

**Comment by wkruijne** [comment]
Blegh, gotta love these vague errors. 
Oddly enough the 'solutions' there get rid of the segfault, but replace it with it a total freeze of  opensesame. 

Plugging headphones in the 'jack' port didn't solve anything either ;) 

Guess I'll just keep an eye out for an update to OpenAL...?

**Comment by smathot** [comment]
Hi guys,

I'm closing this issue, because it falls outside the scope of what we can fix in OpenSesame.

Cheers,
Sebastiaan

**Comment by wkruijne** [comment]
Hi Guys,

Update for future reference:

Turns out this SegFault was unrelated to the error (warning?) messages posted earlier. 
Instead, it was caused by psychopy's 'textstim' function. 

It seemed to be the same issue discussed here:
https://discourse.psychopy.org/t/textstim-lead-to-fatal-python-error-pygame-parachute-segmentation-fault-in-debian-testing/1838/9 ;

Updating pyglet through the NeuroDebian repo to 1.3 has fixed the issue

Finally!
Have a good one,
Wouter
