### ISSUE TITLE
Incorrect "Another version of OpenSesame is already installed..." warning

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#491]
This is a low prio one  :arrow_heading_down: I guess but I though I'd report it:

Even on clean Windows 7 (32 and 64bit) and 10 installs I get the "Another version of OpenSesame is already installed..." warning. And I'm 100% there isn't as there aren't even MS updates or drivers installed on those clean Windows images.

**Comment by smathot** [comment]
Right. It seems that the installer doesn't actually check whether OpenSesame is already installed. I think I'll just change the message then "*If* another version of OpenSesame is already installed …".

**Comment by JdenHartog** [comment]
Sounds like a good solution! :ok_hand:

**Comment by JdenHartog** [comment]
Nice! :+1:
