### ISSUE TITLE
media_player_mpy should register response time

### ISSUE THREAD

**Issue by dschreij** [smathot/OpenSesame#501]
Right now, most OpenSesame items register a response_time variable with the name `response_time_[itemname]`. The media_player_mpy item doesn't do this yet, while it should.

**Comment by smathot** [comment]
Shouldn't this be posted dschreij/opensesame-plugin-mediaplayer ?

In any case, the optimal way to do it is by having `media_player_mpy` inherit two classes: 

- `base_response_item` which provides the basic logic for things that collect responses; and
- `media_player_mpy_mixin`, which provides a `prepare_response_func()`, which in turn should *return* (so not *be*) a function that collects a response.

You can see an example of this logic in the `keyboard_response` item.

If you use this system, OpenSesame will automatically include the responses in the response history etc. Of course, you can also implement a custom way to handle responses, but that wouldn't integrate as nicely.

Does this help at all? I know it's a bit abstract.

**Comment by dschreij** [comment]
You're right, sorry. I had in mind that since it is included with OS it should be placed here, but now that I think of it, I'll recreate the issue in its on repository.
