### ISSUE TITLE
expyriment won't import

### ISSUE THREAD

**Issue by robbertmijn** [smathot/OpenSesame#507]
I just updated to OpenSesame 3.1.5 on my mbp (os Sierra 10.12.3) and expyriment won't import anymore. I get this message when I try to import using debug window:

```
import expyriment
Expyriment 0.8.0 (Python 2.7.12) 
/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/expyriment/misc/_miscellaneous.py:182: RuntimeWarning: use font: dlopen(/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/pygame/font.so, 2): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /Applications/OpenSesame.app/Contents/Resources/lib/libSDL_ttf-2.0.0.dylib
  Reason: image not found
(ImportError: dlopen(/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/pygame/font.so, 2): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /Applications/OpenSesame.app/Contents/Resources/lib/libSDL_ttf-2.0.0.dylib
  Reason: image not found)
  pygame.font.init()

NotImplementedErrorTraceback (most recent call last)
<ipython-input-1-45995d2fe1ac> in <module>()
----> 1 import expyriment

/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/expyriment/__init__.pyc in <module>()
    140 misc.add_fonts(misc.str2unicode(_os.path.abspath(
    141     _os.path.join(_os.path.dirname(__file__),
--> 142                   "_fonts"))))
    143 
    144 try:

/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/expyriment/misc/_miscellaneous.pyc in add_fonts(folder)
    180     """
    181 
--> 182     pygame.font.init()
    183     pygame.sysfont.initsysfonts()
    184 

/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/pygame/__init__.pyc in __getattr__(self, var)
    103         if self.reason:
    104             MissingPygameModule += "\n(%s)" % self.reason
--> 105         raise NotImplementedError(MissingPygameModule)
    106 
    107     def __nonzero__(self):

NotImplementedError: font module not available
(ImportError: dlopen(/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/pygame/font.so, 2): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /Applications/OpenSesame.app/Contents/Resources/lib/libSDL_ttf-2.0.0.dylib
  Reason: image not found)
```

**Comment by smathot** [comment]
@dschreij Robbert and I just tried this on his Macbook. On 3.1.4, `expyriment` fine, but the 3.1.5 packages gives the above error.

**Comment by dschreij** [comment]
I was afraid of this. This is probably a reference to an external file that exists on my system, but not on others. It's hard to test this without a vanilla mac. I think I can fix this one, although I think it's strange that it occurs as I didn't change anything to pygame or freetype since the previous versions. I'll get back soon with a new build.

**Comment by smathot** [comment]
> I'll get back soon with a new build.

Excellent. Yeah for now I've rolled back the link to the Mac OS 3.1.5 package. There have been only a handful of downloads so far, so the damage is limited.

Could you repack it as `opensesame_3.1.5-py2.7-macos-2.dmg` and notify @robbertmijn? He has a fresh(ish) Mac to test it on.

**Comment by dschreij** [comment]
Sure, shall I just upload it to cogsci.nl for now, until it's properly tested? The upload can take a while, because the speeds here are not that terrific.

**Comment by smathot** [comment]
Haha, yes, that's fine.

**Comment by dschreij** [comment]
Ok, I fixed this (I hope). I could actually reproduce this error by renaming 

/usr/local/opt/freetype/lib/libfreetype.6.dylib

to something else so libSDL_ttf couldn't find it. With this new build this error should not occur anymore (but I can't see if anything down the line has broken). The new version is available at http://cogsci.nl/dschreij/opensesame-mac/opensesame_3.1.5-py2.7-macos-2.dmg. 
@smathot If it works, can you place it Github too?

**Comment by smathot** [comment]
Excellent!

**Comment by dschreij** [comment]
Did you test it already?

**Comment by smathot** [comment]
We did, quickly. The import error is indeed gone!

**Comment by dschreij** [comment]
Great to hear!
