### ISSUE TITLE
Mac OS package does not include openpyxl

### ISSUE THREAD

**Issue by smathot** [smathot/OpenSesame#514]
The Mac OS package does not include `openpyxl`, which is required to read `.xlsx` files in the loop.

**Comment by dschreij** [comment]
Right, I created a new package with this dependency included. It's being uploaded as `opensesame_3.1.6-py2.7-macos-2.dmg` on Github right now.

**Comment by smathot** [comment]
Excellent, thank you! I tested it, seems to work, and the documentation is updating as I write this.
