### ISSUE TITLE
fromTheme() takes no keyword arguments

### ISSUE THREAD

**Issue by dev-jam** [smathot/OpenSesame#532]
Using OpenSesame 3.1.6 (Ubuntu PPA) on Debian Stretch.
 
I get an error when adding files in the file pool referring to line 123 of /usr/lib/python2.7/dist-packages/libqtopensesame/misc/theme.py.
fromTheme() does not accept keywords, so 'fallback' should not be given as a keyword, only the value. Patch is attached.
[opensesame_fallback_icon_patch.txt](https://github.com/smathot/OpenSesame/files/968931/opensesame_fallback_icon_patch.txt)

**Comment by smathot** [comment]
Thanks. But this issue has already been fixed (92f4b9f)!
