### ISSUE TITLE
Color specifications breaks if RGB values are of numpy.int type

### ISSUE THREAD

**Issue by eort** [smathot/OpenSesame#533]
Hi, 

When passing a tuple of numpy integers as colors to a canvas function, Opensesame crashes and complains that `(R,G,B)` is an invalid color specification. Not sure whether it is worth to include numpy integers to the list of allowed types, but in any case, a more detailed error message would be helpful (there is no way you can distinguish a normal integer from a numpy integer. 

Eduard

**Comment by smathot** [comment]
Hi Eduard,

Thanks!

I don't actually see this problem, but that it might be numpy-version specific. Do you have an example that triggers the issue, plus a full stracktrace?

And would you like to give this a go yourself? `openexp/_color/color.py` is the place to be. I think it should be easy to fix.

Cheers,
Sebastiaan

**Comment by eort** [comment]
Yes, I wanted to give it a try anyway. Only I am a  little busy these days. If it can wait 2-3 weeks I'll gladly go for it. 

On a slightly related matter, why isn't possible anymore to pass RGB values in lists to canvas functions? Not that it matters that much, but it was one of the few things that broke my experiments when I switched to Opensesame >3.x

Here an example of what I mean: 
~~~.python
import numpy as np

cv = canvas()
kb = keyboard()
col = [np.int16(i) for i in [232,12,123]]
cv.circle(0,0,20,color = tuple(col2))

cv.show()
kb.get_key()
~~~

Eduard

**Comment by eort** [comment]
Hi Sebastiaan, 

I had a look at that issue again and I reconsidered it somewhat. 

For one, situations in which users end up with np.integers in a regular tuple are likely to occur. If anything users would pass a numpy array as color argument. So, it would make more sense to implement a general numpy support rather than selectively allow numpy integers only. 

This brings me to another point. When I looked up how `webcolors` deals with the type of RGB values passed to it, I realised that it is quite flexible (and a little careless). Specifically, webcolors will work as long as the rgb-triplet passed to it is a number (float or integer), irrespective of the specific type. 

So, before I start to implement something that is not desirable, I wanted to make sure I understand your reasoning of designing color.py the way you did. 

Based on my understanding my idea of how rgb values as color argument  should be handled is following: 
1) Check whether RGB values are passed in some form of container (tuple, list, np.array)
~~~,python
# e.g. like so:
conTypes = (list,tuple,np.array)    
if isinstance(colorspec, conTypes): pass
~~~
2) For every item in the container, check whether it is a number between 0 and 255

3) If everything is save, pass it to webcolors. 

What is your take on that? Do I miss anything important?

Eduard
