### ISSUE TITLE
Catch failed mixer init in legacy backend

### ISSUE THREAD

**Issue by smathot** [smathot/OpenSesame#541]
Currently, a `pygame.error` sometimes occurs when calling `pygame.mixer()`. This prevents running the experiment, but could easily be caught to at least allow for soundless experiments.

**Comment by JdenHartog** [comment]
Hi Sebastiaan,

When trying to fix this for the Psychopy back-end as well by changing [openexp/_canvas/psycho.py](https://github.com/smathot/OpenSesame/blob/master/openexp/_canvas/psycho.py#L403)
```
	pygame.mixer.init()
```
to
```
	try:
		pygame.mixer.init()
	except:
		print(u'openexp._canvas.psycho.init_display(): failed to initialize mixer')
```

I think I discovered pygame.mixer is also initialized by sampler (even when not using a sampler item).
The output I get when running the *default template* with the psycho back-end  acknowledges this see 
`openexp.sampler._legacy.init_sound():` below

>Starting experiment as ExperimentProcess-3
C:\Program Files (x86)\OpenSesame\lib\site-packages\openexp\_canvas\psycho.py:56: UserWarning: Your PsychoPy version is outdated. To draw complex shapes that include holes, concavities, etc., please update to PsychoPy version 1.84.1 or higher.
  warnings.warn(u'Your PsychoPy version is outdated. To draw complex '
openexp._canvas.psycho.init_display(): waitblanking = True
openexp._canvas.psycho.init_display(): monitor = testMonitor
openexp._canvas.psycho.init_display(): screen = 0
**openexp.sampler._legacy.init_sound(): sampling freq = 48000, buffer size = 1024**
**openexp.sampler._legacy.init_sound(): mixer already initialized, closing**
experiment.run(): experiment started at Wed Jul 26 14:20:19 2017
experiment.run(): disabling garbage collection
experiment.run(): experiment finished at Wed Jul 26 14:20:21 2017
experiment.end(): enabling garbage collection
done!

Shall I make a pull request for removing
```
	pygame.mixer.init()
```
from [openexp/_canvas/psycho.py](https://github.com/smathot/OpenSesame/blob/master/openexp/_canvas/psycho.py#L403)? Or do you think this will break something on Mac OS or Ubuntu systems?

**Comment by smathot** [comment]
Thanks for looking into this. Yes, I don't see why initializing the mixer in the PsychoPy canvas is necessary, or even makes sense. So feel free to remove it.

As a suggestion (which is not relevant if you're going to remove the init altogether), it's always better to specify which `Exception` you will catch, instead of doing a black `except:`. So: `except pygame.error:` in this case.

**Comment by JdenHartog** [comment]
OK. great! > Done!

You think it would be safe to remove this for the [expyriment back-end](https://github.com/smathot/expyriment/blob/master/expyriment/control/_experiment_control.py#L320) two? Deleting:
```
if defaults.audiosystem_autostart:
    mixer.init()
    mixer.init() # Needed on some systems
```

And if you want me to make a pull-request for that; on [what branch](https://github.com/smathot/expyriment)?
