### ISSUE TITLE
xpyriment _canvas module is not being used for timing accuracy.

### ISSUE THREAD

**Issue by imnotamember** [smathot/OpenSesame#542]
Hello Devs,

While updating my code for my PyNetstation Plug-in I noticed the xpyriment _canvas module is using only the options of "0" or "1" for using OpenGL for visual timing accuracy. This is an issue because in the xpyriment documentation it is suggested that there are 4 options for visual presentation in regards to OpenGL ([link to page](http://docs.expyriment.org/expyriment.control.defaults.html)):
```
open_gl : int or bool
    0/False = no OpenGL (no vsync / no blocking)
    1       = OpenGL (vsync / no blocking)
    2       = OpenGL (vsync / blocking)
    3       = OpenGL (vsync / alternative blocking)
    
    NOTES
    =====
    no OpenGL (no vsync / no blocking)
    ----------------------------------
    * Short preloading times
        Pygame is used to write directly to the display
    * Unsynchronized display updating
        Pixels are starting to change at wherever the vertical retrace is
        at the moment of presentation
    
    This mode can be useful for dynamic displays, where an accurate
    stimulus timing is not required, but rather very fast display changes
    have high priority and stimuli have to be created and on the fly (e.g.
    questionnairs, video game-like scenarios).
    
    OpenGL (vsync / no blocking)
    ----------------------------
    * Longer preloading times
        OpenGL is used to write to the display and a conversion to an
        OpenGL texture is needed
    * Synchronized display updating
        Pixels are starting to change always when the vertical retrace is
        at the left top corner
    * Innaccurate presentation time reporting
        Exact time of pixels changing on screen is not known
        
    This mode can be useful for dynamic displays, where an accurate
    stimulus timing is not required, but rather fast and fluid (e.g.
    non-tearing) display changes have high priority and preloaded stimuli
    can be used (e.g. well-controlled motion stimuli).

    OpenGL (vsync / blocking)
    -------------------------
    * Longer preloading times
        OpenGL is used to write to the display and a conversion to an
        OpenGL texture is needed
    * Synchronized display updating
        Pixels are starting to change always when the vertical retrace is
        at the left top corner
    * Accurate presentation time reporting
        present() method will only return when all drawing has been
        finished

    This can be useful for static stimulus presentation, where getting an
    accurate  presentation time report is of highest priority. Since this
    will be the case for most psychological and neuroscientific settings,
    it is the default mode used by Expyriment.

    OpenGL (vsync / alternative blocking)
    -------------------------------------
    * Longer preloading times
        OpenGL is used to write to the display and a conversion to an
        OpenGL texture is needed
    * Synchronized display updating
        Pixels are starting to change always when the vertical retrace is
        at the left top corner
    * Accurate presentation time reporting (alternative method)
        present() method will only return when all drawing has been
        finished and the then empty back buffer is available for drawing
        on it again

    This can be useful for static stimulus presentation, where getting an
    accurate presentation time report is of highest priority and the
    former mode does not work correctly (due to different video card
    driver implementations).
```
[Here](https://github.com/smathot/OpenSesame/blob/master/openexp/_canvas/xpyriment.py) is a link to the file that is causing OpenSesame to use either option "0/False" or "1/True," both of which result in unreliable timing information according to the documentation. The code in particular is line 260-261, which appears to take the user-defined settings in the xpyriment backend settings in the GUI.
```
		control.defaults.open_gl = experiment.var.get(u'expyriment_opengl',
			xpyriment.settings[u'expyriment_opengl'][u'default']) == u'yes'
```

I propose the xpyriment backend settings screen include brief explanation of options 0-3 as well as implementation of those specific options in the xpyriment canvas file. Something simple like this perhaps:
> 0 = No OpenGL
> 1 = OpenGL with inaccurate presentation times
> 2 = OpenGL with accurate presentation times
> 3 = Alternative OpenGL with accurate presentation times

And for the code:
`control.defaults.open_gl = experiment.var.get(u'expyriment_opengl')`
assuming that is proper format for the access of the user's choice.

I would have submitted this as a pull request but wasn't sure if there are other things going on that I'm too naive to have noticed. Hope this is helpful/informative. Thanks for all the hardwork that has gone into this project so far.
Best,
Josh Zosky

**Comment by smathot** [comment]
Hi Josh,

Thanks for pointing this out. It seems that this has changed in Expyriment 0.8. Before that, the `open_gl` setting was just a `bool`.

@fladd @lindemann09 Should we indeed switch to using `open_gl = 2` by default? And then probably allow the user to configure this properly?

Strange thing: I have tested the xpyriment backend quite extensively with this 1 setting, and timing was generally fine.

Cheers,
Sebastiaan

**Comment by fladd** [comment]
Hi guys,

indeed, `2` is similar to the former `True`. More importantly, though, we mapped `True` to `2` internally, in order to not break backwards compatibility! So if OpenSesame is using `True` (and not `1`), then things will still work as they did!

You could also think about switching to `3`, which is the alternative blocking mode.
What this does is simply to present a transparent pixel on the back buffer, before calling `GL_Finish`. In our experience, some video card drivers need this in order to block on the vertical retrace (e.g. MacBook Pro). However, I should mention that we do **not** have a lot of data on whether there are any downsides using this option as default (e.g. for other devices that otherwise work fine with the normal blocking). And hence we still use `2` as default in Expyriment, but suggest to always run the test suite to check whether the timing is accurate (and try again with alternative blocking, if necessary).

I would suggest to do the same for OpenSesame. Use a reasonable default, let the user change the setting, and provide a means for testing visual presentation accuracy.

I hope this helps.

Best,
Florian

**Comment by smathot** [comment]
Thanks for clearing this up. OpenSesame indeed uses boolean `True` so that explain why things still work fine. I'll assign it to 3.1.8, because there's not urgency here.

And Josh, thanks for bringing this up! Very useful.
